# -*- coding: utf-8 -*-
"""Gerenciador de colaboradores.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a_DXoHtuHTRbg6G1QyLbJYORi2KZw3ht

#Código do gerenciador de colaboradores
"""

#Gerenciador de colaboradores
#----------Início das Variáveis Globais----------
lista_colaboradores = []
id_global = 0

#----------Fim das Variáveis Globais----------

#Início do cadastro de colaboradores

def cadastrar_colaborador(id_global):
  print('******************************************************************\n'+
        '--------------------MENU CADASTRAR COLABORADOR--------------------')
  nome = input('Por favor entre com o nome:')
  setor = input('Por favor entre com o setor:')
  pagamento = int(input('Por favor entre com o pagamento(R$):'))
  id_colaborador = {'id' : id_global, #Dicionário dos colaboradores
                    'nome' : nome,
                    'setor' : setor,
                    'pagamento' : pagamento}
  lista_colaboradores.append(id_colaborador.copy())#A lista de todos os colaboradores sendo agrupada aqui

#Fim do cadastro de colaboradores

#Início da consulta de colaboradores

def consultar_colaborador(): #Função de consultar colaborador
  print('******************************************************************\n'+
        '--------------------MENU CONSULTAR COLABORADOR--------------------')
  while True:
    consultar = input('\nEscolha a opção desejada:\n'+ #Menu com as 3 opções de consulta e opção para voltar ao menu
                      '1- Consultar Todos os colaboradores\n'+
                      '2- Consultar Colaborador por id\n'+
                      '3- Consultar Colaborador(es)por setor\n'
                      '4- Retornar\n'+
                      '>>')
    if consultar == '1':
      print('Você escolheu a opção Consultar TODOS os colaboradores')
      for colaborador in lista_colaboradores:#Varrer a lista de colaboradores
       print('------------------------------------------------------')
       for chave, valor in colaborador.items():#Varrer os conjuntos chave e valor do dicionário dos colaboradores
        print('{}: {}'.format(chave, valor)) #Mostrar todos os colaboradores depois de varrer a lista com os dicionários
      print('------------------------------------------------------')

    elif consultar == '2':
     print('Você escolheu a opção Consultar colaborador(es)por id')
     id_desejado = int(input('Digite o id do colaborador:')) #Pedir o id desejado para consulta
     for colaborador in lista_colaboradores :
       if colaborador['id'] == id_desejado : #Se o valor do id do colaborador for igual ao id desejado
        print('------------------------------------------------------')
        for chave, valor in colaborador.items():
         print('{}: {}'.format(chave, valor)) #Mostrar o colaborador com id escolhido
        print('------------------------------------------------------')

    elif consultar == '3': #Consultar por setor
     print('Você escolheu a opção Consultar colaborador(es)por setor')
     setor_desejado = input('Digite o setor do colaborador:') #Pedir qual setor para consulta
     for colaborador in lista_colaboradores :
       if colaborador['setor'] == setor_desejado : #o valor do id do colaborador é igual ao id desejado
        print('------------------------------------------------------')
        for chave, valor in colaborador.items():
         print('{}: {}'.format(chave, valor)) #Mostrar os colaboradores do setor escolhido
        print('------------------------------------------------------')

    elif consultar == '4': #Voltar para o Menu principal
     return
    else:
      print('Opção Inválida. Tente Novamente.') #Mensagem de erro caso seja digitado algo diferente de 1,2,3,4
      continue #Volta para o início do laço

#Fim da consulta de colaboradores

#Início do remover colaboradores

def remover_colaborador(): #Função de remover colaborador
  print('****************************************************************\n'+
        '--------------------MENU REMOVER COLABORADOR--------------------') #Menu de remover colaborador
  remover_id = int(input('Digite o id do colaborador a ser removido:')) #Pedir qual id de colaborador para ser removido
  for colaborador in lista_colaboradores: #Procurar na lista de colaboradores
    if colaborador['id'] == remover_id: #Se o id escolhido for igual ao de algum colaborador da lista
      lista_colaboradores.remove(colaborador) #Remover colaborador escolhido
      print('Colaborador removido do programa.')

#Fim do remover colaboradores

#Início do Main
print('Bem vindo ao Controle de colaboradores do Eduardo') #Mensagem de boas vindas com meu nome
while True:
  menu_principal =input('******************************************************************\n'+ #Menu principal com as 4 opções
                        '--------------------------MENU PRINCIPAL--------------------------'
                        '\nEscolha a opção desejada:\n'+
                        '1- Cadastrar Colaborador\n'+
                        '2- Consultar Colaborador(es)\n'+
                        '3- Remover Colaborador\n'
                        '4- Sair\n'+
                        '>>')
  if menu_principal == '1': #Ir para cadastrar colaborador e adicionar +1 para o id global
   id_global = id_global + 1
   cadastrar_colaborador(id_global)

  elif menu_principal == '2': #Ir para a consulta de colaborador(es)
   consultar_colaborador()

  elif menu_principal == '3': #Ir para remover colaborador
   remover_colaborador()

  elif menu_principal == '4': #Encerrar programa
   break
  else: #Mensagem de erro
    print('Opção Inválida. Tente Novamente.')
    continue #Volta para o início do laço
#Fim do Main